In [1]:
import pandas as pd

In [2]:
pd

In [3]:
df = pd.read_csv("data.csv")

In [4]:
df

,id,date,first_name,last_name,email,gender,ip_address,country,price_paid,tax
0,1,03/28/2021,Marylin,Alders,malders0@shop-pro.jp,Male,160.119.8.119,Canada,$5.36,NaN
1,2,03/19/2021,Hinda,Harridge,hharridge1@gnu.org,Female,210.51.172.132,Canada,$8.32,NaN
2,3,03/17/2021,Erl,Kilminster,ekilminster2@etsy.com,Male,213.8.101.145,United States,$3.73,20.0
3,4,03/19/2021,Grata,Brantl,gbrantl3@umn.edu,Female,5.140.237.101,United States,$3.70,20.0
4,5,03/24/2021,Kanya,Beasant,kbeasant4@jigsy.com,Male,106.252.162.233,Morocco,$9.24,20.0
...,...,...,...,...,...,...,...,...,...,...
995,996,03/24/2021,Duff,Errigo,derrigorn@elpais.com,Female,193.84.247.144,France,$3.63,NaN
996,997,03/17/2021,Ame,Rastall,arastallro@toplist.cz,Female,188.219.12.109,NaN,$4.59,20.0
997,998,03/13/2021,Betty,Stickels,bstickelsrp@cloudflare.com,Male,199.80.60.87,United States,$7.54,20.0
998,999,03/17/2021,Paquito,Tesoe,ptesoerq@rakuten.co.jp,Male,0.183.63.11,United States,$5.81,NaN
999,1000,03/23/2021,Rochelle,Pringuer,rpringuerrr@house.gov,NaN,170.193.249.83,Canada,$8.01,20.0

In [5]:
# Afficher les 5 premières lignes
df.head()

,id,date,first_name,last_name,email,gender,ip_address,country,price_paid,tax
0,1,03/28/2021,Marylin,Alders,malders0@shop-pro.jp,Male,160.119.8.119,Canada,$5.36,NaN
1,2,03/19/2021,Hinda,Harridge,hharridge1@gnu.org,Female,210.51.172.132,Canada,$8.32,NaN
2,3,03/17/2021,Erl,Kilminster,ekilminster2@etsy.com,Male,213.8.101.145,United States,$3.73,20.0
3,4,03/19/2021,Grata,Brantl,gbrantl3@umn.edu,Female,5.140.237.101,United States,$3.70,20.0
4,5,03/24/2021,Kanya,Beasant,kbeasant4@jigsy.com,Male,106.252.162.233,Morocco,$9.24,20.0

In [6]:
# Afficher les 5 dernières lignes
df.tail()

,id,date,first_name,last_name,email,gender,ip_address,country,price_paid,tax
995,996,03/24/2021,Duff,Errigo,derrigorn@elpais.com,Female,193.84.247.144,France,$3.63,NaN
996,997,03/17/2021,Ame,Rastall,arastallro@toplist.cz,Female,188.219.12.109,NaN,$4.59,20.0
997,998,03/13/2021,Betty,Stickels,bstickelsrp@cloudflare.com,Male,199.80.60.87,United States,$7.54,20.0
998,999,03/17/2021,Paquito,Tesoe,ptesoerq@rakuten.co.jp,Male,0.183.63.11,United States,$5.81,NaN
999,1000,03/23/2021,Rochelle,Pringuer,rpringuerrr@house.gov,NaN,170.193.249.83,Canada,$8.01,20.0

In [7]:
df.head(10)

,id,date,first_name,last_name,email,gender,ip_address,country,price_paid,tax
0,1,03/28/2021,Marylin,Alders,malders0@shop-pro.jp,Male,160.119.8.119,Canada,$5.36,NaN
1,2,03/19/2021,Hinda,Harridge,hharridge1@gnu.org,Female,210.51.172.132,Canada,$8.32,NaN
2,3,03/17/2021,Erl,Kilminster,ekilminster2@etsy.com,Male,213.8.101.145,United States,$3.73,20.0
3,4,03/19/2021,Grata,Brantl,gbrantl3@umn.edu,Female,5.140.237.101,United States,$3.70,20.0
4,5,03/24/2021,Kanya,Beasant,kbeasant4@jigsy.com,Male,106.252.162.233,Morocco,$9.24,20.0
5,6,03/25/2021,Titos,Braybrooke,tbraybrooke5@umn.edu,Female,173.100.21.179,United States,$5.82,NaN
6,7,03/14/2021,Ava,Kencott,akencott6@phoca.cz,Female,118.251.45.43,Canada,$6.29,NaN
7,8,03/08/2021,Codi,Feasley,cfeasley7@ed.gov,Male,26.190.191.249,France,$3.01,20.0
8,9,03/09/2021,Waylon,Heersema,wheersema8@tumblr.com,Male,63.242.174.112,Canada,$3.70,20.0
9,10,03/23/2021,Guglielma,Gookes,ggookes9@amazon.co.uk,Male,169.100.6.0,France,$9.05,NaN

In [8]:
# Récupérer des éléments de 10 à 19
df[10:20]

,id,date,first_name,last_name,email,gender,ip_address,country,price_paid,tax
10,11,03/11/2021,Lief,Woodcraft,lwoodcrafta@sitemeter.com,Male,201.76.240.51,Canada,$5.71,NaN
11,12,03/16/2021,Bailie,Wyman,bwymanb@lulu.com,Male,222.60.138.222,United States,$3.15,20.0
12,13,03/05/2021,Janice,Morillas,jmorillasc@miibeian.gov.cn,Female,24.25.198.252,Canada,$5.30,20.0
13,14,03/24/2021,Cull,Vassie,cvassied@unblog.fr,NaN,18.203.61.94,France,$5.97,20.0
14,15,03/21/2021,Oralie,Maryon,omaryone@va.gov,Female,215.248.16.198,United States,$4.53,20.0
15,16,03/24/2021,Julina,Faint,jfaintf@amazon.co.jp,Female,96.193.4.151,United States,$4.10,20.0
16,17,03/27/2021,Eve,Allaway,eallawayg@ebay.co.uk,Female,184.107.59.156,United States,$6.44,20.0
17,18,03/20/2021,Esta,Boulden,ebouldenh@posterous.com,NaN,220.109.140.190,United States,$3.16,20.0
18,19,03/16/2021,Judye,Behan,jbehani@google.es,Female,27.196.2.18,France,$4.90,20.0
19,20,03/01/2021,Sibeal,Mounch,smounchj@rakuten.co.jp,Male,218.17.7.177,Canada,$5.82,20.0

In [9]:
# Récupérer des éléments de 10 à 20
df.loc[10:20]

,id,date,first_name,last_name,email,gender,ip_address,country,price_paid,tax
10,11,03/11/2021,Lief,Woodcraft,lwoodcrafta@sitemeter.com,Male,201.76.240.51,Canada,$5.71,NaN
11,12,03/16/2021,Bailie,Wyman,bwymanb@lulu.com,Male,222.60.138.222,United States,$3.15,20.0
12,13,03/05/2021,Janice,Morillas,jmorillasc@miibeian.gov.cn,Female,24.25.198.252,Canada,$5.30,20.0
13,14,03/24/2021,Cull,Vassie,cvassied@unblog.fr,NaN,18.203.61.94,France,$5.97,20.0
14,15,03/21/2021,Oralie,Maryon,omaryone@va.gov,Female,215.248.16.198,United States,$4.53,20.0
15,16,03/24/2021,Julina,Faint,jfaintf@amazon.co.jp,Female,96.193.4.151,United States,$4.10,20.0
16,17,03/27/2021,Eve,Allaway,eallawayg@ebay.co.uk,Female,184.107.59.156,United States,$6.44,20.0
17,18,03/20/2021,Esta,Boulden,ebouldenh@posterous.com,NaN,220.109.140.190,United States,$3.16,20.0
18,19,03/16/2021,Judye,Behan,jbehani@google.es,Female,27.196.2.18,France,$4.90,20.0
19,20,03/01/2021,Sibeal,Mounch,smounchj@rakuten.co.jp,Male,218.17.7.177,Canada,$5.82,20.0
20,21,03/12/2021,Jeffrey,Stanman,jstanmank@latimes.com,Female,3.110.64.192,France,$5.55,20.0

In [10]:
df.shape

(1000, 10)

In [11]:
df.columns.tolist()

['id',
 'date',
 'first_name',
 'last_name',
 'email',
 'gender',
 'ip_address',
 'country',
 'price_paid',
 'tax']

In [12]:
df_email = df.set_index("email")

In [13]:
df_email.loc[['cvassied@unblog.fr', 'smounchj@rakuten.co.jp']]

,id,date,first_name,last_name,gender,ip_address,country,price_paid,tax
email,,,,,,,,,
cvassied@unblog.fr,14,03/24/2021,Cull,Vassie,NaN,18.203.61.94,France,$5.97,20.0
smounchj@rakuten.co.jp,20,03/01/2021,Sibeal,Mounch,Male,218.17.7.177,Canada,$5.82,20.0

In [14]:
# Filter les hommes
df[df.gender=="Male"]

,id,date,first_name,last_name,email,gender,ip_address,country,price_paid,tax
0,1,03/28/2021,Marylin,Alders,malders0@shop-pro.jp,Male,160.119.8.119,Canada,$5.36,NaN
2,3,03/17/2021,Erl,Kilminster,ekilminster2@etsy.com,Male,213.8.101.145,United States,$3.73,20.0
4,5,03/24/2021,Kanya,Beasant,kbeasant4@jigsy.com,Male,106.252.162.233,Morocco,$9.24,20.0
7,8,03/08/2021,Codi,Feasley,cfeasley7@ed.gov,Male,26.190.191.249,France,$3.01,20.0
8,9,03/09/2021,Waylon,Heersema,wheersema8@tumblr.com,Male,63.242.174.112,Canada,$3.70,20.0
...,...,...,...,...,...,...,...,...,...,...
991,992,03/07/2021,Elihu,Crush,ecrushrj@berkeley.edu,Male,174.38.173.53,Morocco,$5.05,20.0
992,993,03/04/2021,Maurene,Guilloneau,mguilloneaurk@about.me,Male,108.73.141.204,France,$9.19,NaN
993,994,03/22/2021,Ossie,Snelle,osnellerl@nhs.uk,Male,230.187.67.246,France,$4.31,NaN
997,998,03/13/2021,Betty,Stickels,bstickelsrp@cloudflare.com,Male,199.80.60.87,United States,$7.54,20.0
998,999,03/17/2021,Paquito,Tesoe,ptesoerq@rakuten.co.jp,Male,0.183.63.11,United States,$5.81,NaN

In [15]:
# filter sur la France et le Canada 
country_filter = df.country.isin(['France', 'Canada'])
df[country_filter]

,id,date,first_name,last_name,email,gender,ip_address,country,price_paid,tax
0,1,03/28/2021,Marylin,Alders,malders0@shop-pro.jp,Male,160.119.8.119,Canada,$5.36,NaN
1,2,03/19/2021,Hinda,Harridge,hharridge1@gnu.org,Female,210.51.172.132,Canada,$8.32,NaN
6,7,03/14/2021,Ava,Kencott,akencott6@phoca.cz,Female,118.251.45.43,Canada,$6.29,NaN
7,8,03/08/2021,Codi,Feasley,cfeasley7@ed.gov,Male,26.190.191.249,France,$3.01,20.0
8,9,03/09/2021,Waylon,Heersema,wheersema8@tumblr.com,Male,63.242.174.112,Canada,$3.70,20.0
...,...,...,...,...,...,...,...,...,...,...
992,993,03/04/2021,Maurene,Guilloneau,mguilloneaurk@about.me,Male,108.73.141.204,France,$9.19,NaN
993,994,03/22/2021,Ossie,Snelle,osnellerl@nhs.uk,Male,230.187.67.246,France,$4.31,NaN
994,995,03/17/2021,Carolyne,Bruntjen,cbruntjenrm@reference.com,Female,7.29.168.78,France,$5.68,20.0
995,996,03/24/2021,Duff,Errigo,derrigorn@elpais.com,Female,193.84.247.144,France,$3.63,NaN
999,1000,03/23/2021,Rochelle,Pringuer,rpringuerrr@house.gov,NaN,170.193.249.83,Canada,$8.01,20.0

In [16]:
# Filtrer sur le price_paid (price_paid >= 6)

df_test = df.copy()
df_test.price_paid = df_test.price_paid.apply(lambda x : x.replace("$", ""))
df_test.price_paid = df_test.price_paid.astype(float)
df_test[df_test.price_paid >= 6.0]

,id,date,first_name,last_name,email,gender,ip_address,country,price_paid,tax
1,2,03/19/2021,Hinda,Harridge,hharridge1@gnu.org,Female,210.51.172.132,Canada,8.32,NaN
4,5,03/24/2021,Kanya,Beasant,kbeasant4@jigsy.com,Male,106.252.162.233,Morocco,9.24,20.0
6,7,03/14/2021,Ava,Kencott,akencott6@phoca.cz,Female,118.251.45.43,Canada,6.29,NaN
9,10,03/23/2021,Guglielma,Gookes,ggookes9@amazon.co.uk,Male,169.100.6.0,France,9.05,NaN
16,17,03/27/2021,Eve,Allaway,eallawayg@ebay.co.uk,Female,184.107.59.156,United States,6.44,20.0
...,...,...,...,...,...,...,...,...,...,...
989,990,03/16/2021,Horatius,Van Arsdalen,hvanarsdalenrh@prlog.org,NaN,243.214.103.52,France,8.69,20.0
990,991,03/19/2021,Shep,Thorburn,sthorburnri@prnewswire.com,Male,108.123.252.15,France,7.02,20.0
992,993,03/04/2021,Maurene,Guilloneau,mguilloneaurk@about.me,Male,108.73.141.204,France,9.19,NaN
997,998,03/13/2021,Betty,Stickels,bstickelsrp@cloudflare.com,Male,199.80.60.87,United States,7.54,20.0
999,1000,03/23/2021,Rochelle,Pringuer,rpringuerrr@house.gov,NaN,170.193.249.83,Canada,8.01,20.0

In [17]:
# Supprimer une colonne
df.drop("ip_address", axis=1)

,id,date,first_name,last_name,email,gender,country,price_paid,tax
0,1,03/28/2021,Marylin,Alders,malders0@shop-pro.jp,Male,Canada,$5.36,NaN
1,2,03/19/2021,Hinda,Harridge,hharridge1@gnu.org,Female,Canada,$8.32,NaN
2,3,03/17/2021,Erl,Kilminster,ekilminster2@etsy.com,Male,United States,$3.73,20.0
3,4,03/19/2021,Grata,Brantl,gbrantl3@umn.edu,Female,United States,$3.70,20.0
4,5,03/24/2021,Kanya,Beasant,kbeasant4@jigsy.com,Male,Morocco,$9.24,20.0
...,...,...,...,...,...,...,...,...,...
995,996,03/24/2021,Duff,Errigo,derrigorn@elpais.com,Female,France,$3.63,NaN
996,997,03/17/2021,Ame,Rastall,arastallro@toplist.cz,Female,NaN,$4.59,20.0
997,998,03/13/2021,Betty,Stickels,bstickelsrp@cloudflare.com,Male,United States,$7.54,20.0
998,999,03/17/2021,Paquito,Tesoe,ptesoerq@rakuten.co.jp,Male,United States,$5.81,NaN
999,1000,03/23/2021,Rochelle,Pringuer,rpringuerrr@house.gov,NaN,Canada,$8.01,20.0

In [18]:
# Spprimer toutes les lignes avec gender "Male"
df

,id,date,first_name,last_name,email,gender,ip_address,country,price_paid,tax
0,1,03/28/2021,Marylin,Alders,malders0@shop-pro.jp,Male,160.119.8.119,Canada,$5.36,NaN
1,2,03/19/2021,Hinda,Harridge,hharridge1@gnu.org,Female,210.51.172.132,Canada,$8.32,NaN
2,3,03/17/2021,Erl,Kilminster,ekilminster2@etsy.com,Male,213.8.101.145,United States,$3.73,20.0
3,4,03/19/2021,Grata,Brantl,gbrantl3@umn.edu,Female,5.140.237.101,United States,$3.70,20.0
4,5,03/24/2021,Kanya,Beasant,kbeasant4@jigsy.com,Male,106.252.162.233,Morocco,$9.24,20.0
...,...,...,...,...,...,...,...,...,...,...
995,996,03/24/2021,Duff,Errigo,derrigorn@elpais.com,Female,193.84.247.144,France,$3.63,NaN
996,997,03/17/2021,Ame,Rastall,arastallro@toplist.cz,Female,188.219.12.109,NaN,$4.59,20.0
997,998,03/13/2021,Betty,Stickels,bstickelsrp@cloudflare.com,Male,199.80.60.87,United States,$7.54,20.0
998,999,03/17/2021,Paquito,Tesoe,ptesoerq@rakuten.co.jp,Male,0.183.63.11,United States,$5.81,NaN
999,1000,03/23/2021,Rochelle,Pringuer,rpringuerrr@house.gov,NaN,170.193.249.83,Canada,$8.01,20.0

In [19]:
df.set_index("gender", inplace=True)

In [20]:
df.drop("Male", axis=0)

,id,date,first_name,last_name,email,ip_address,country,price_paid,tax
gender,,,,,,,,,
Female,2,03/19/2021,Hinda,Harridge,hharridge1@gnu.org,210.51.172.132,Canada,$8.32,NaN
Female,4,03/19/2021,Grata,Brantl,gbrantl3@umn.edu,5.140.237.101,United States,$3.70,20.0
Female,6,03/25/2021,Titos,Braybrooke,tbraybrooke5@umn.edu,173.100.21.179,United States,$5.82,NaN
Female,7,03/14/2021,Ava,Kencott,akencott6@phoca.cz,118.251.45.43,Canada,$6.29,NaN
Female,13,03/05/2021,Janice,Morillas,jmorillasc@miibeian.gov.cn,24.25.198.252,Canada,$5.30,20.0
...,...,...,...,...,...,...,...,...,...
NaN,990,03/16/2021,Horatius,Van Arsdalen,hvanarsdalenrh@prlog.org,243.214.103.52,France,$8.69,20.0
Female,995,03/17/2021,Carolyne,Bruntjen,cbruntjenrm@reference.com,7.29.168.78,France,$5.68,20.0
Female,996,03/24/2021,Duff,Errigo,derrigorn@elpais.com,193.84.247.144,France,$3.63,NaN
Female,997,03/17/2021,Ame,Rastall,arastallro@toplist.cz,188.219.12.109,NaN,$4.59,20.0
NaN,1000,03/23/2021,Rochelle,Pringuer,rpringuerrr@house.gov,170.193.249.83,Canada,$8.01,20.0

In [21]:
df

,id,date,first_name,last_name,email,ip_address,country,price_paid,tax
gender,,,,,,,,,
Male,1,03/28/2021,Marylin,Alders,malders0@shop-pro.jp,160.119.8.119,Canada,$5.36,NaN
Female,2,03/19/2021,Hinda,Harridge,hharridge1@gnu.org,210.51.172.132,Canada,$8.32,NaN
Male,3,03/17/2021,Erl,Kilminster,ekilminster2@etsy.com,213.8.101.145,United States,$3.73,20.0
Female,4,03/19/2021,Grata,Brantl,gbrantl3@umn.edu,5.140.237.101,United States,$3.70,20.0
Male,5,03/24/2021,Kanya,Beasant,kbeasant4@jigsy.com,106.252.162.233,Morocco,$9.24,20.0
...,...,...,...,...,...,...,...,...,...
Female,996,03/24/2021,Duff,Errigo,derrigorn@elpais.com,193.84.247.144,France,$3.63,NaN
Female,997,03/17/2021,Ame,Rastall,arastallro@toplist.cz,188.219.12.109,NaN,$4.59,20.0
Male,998,03/13/2021,Betty,Stickels,bstickelsrp@cloudflare.com,199.80.60.87,United States,$7.54,20.0
Male,999,03/17/2021,Paquito,Tesoe,ptesoerq@rakuten.co.jp,0.183.63.11,United States,$5.81,NaN
NaN,1000,03/23/2021,Rochelle,Pringuer,rpringuerrr@house.gov,170.193.249.83,Canada,$8.01,20.0

In [23]:
# Supprimer les colonnes 'emails', 'ip_address'
df.drop(['email','ip_address'], axis=1)

,id,date,first_name,last_name,country,price_paid,tax
gender,,,,,,,
Male,1,03/28/2021,Marylin,Alders,Canada,$5.36,NaN
Female,2,03/19/2021,Hinda,Harridge,Canada,$8.32,NaN
Male,3,03/17/2021,Erl,Kilminster,United States,$3.73,20.0
Female,4,03/19/2021,Grata,Brantl,United States,$3.70,20.0
Male,5,03/24/2021,Kanya,Beasant,Morocco,$9.24,20.0
...,...,...,...,...,...,...,...
Female,996,03/24/2021,Duff,Errigo,France,$3.63,NaN
Female,997,03/17/2021,Ame,Rastall,NaN,$4.59,20.0
Male,998,03/13/2021,Betty,Stickels,United States,$7.54,20.0
Male,999,03/17/2021,Paquito,Tesoe,United States,$5.81,NaN
NaN,1000,03/23/2021,Rochelle,Pringuer,Canada,$8.01,20.0

In [24]:
# Supprimer 'id'
del df['id']

In [25]:
df

,date,first_name,last_name,email,ip_address,country,price_paid,tax
gender,,,,,,,,
Male,03/28/2021,Marylin,Alders,malders0@shop-pro.jp,160.119.8.119,Canada,$5.36,NaN
Female,03/19/2021,Hinda,Harridge,hharridge1@gnu.org,210.51.172.132,Canada,$8.32,NaN
Male,03/17/2021,Erl,Kilminster,ekilminster2@etsy.com,213.8.101.145,United States,$3.73,20.0
Female,03/19/2021,Grata,Brantl,gbrantl3@umn.edu,5.140.237.101,United States,$3.70,20.0
Male,03/24/2021,Kanya,Beasant,kbeasant4@jigsy.com,106.252.162.233,Morocco,$9.24,20.0
...,...,...,...,...,...,...,...,...
Female,03/24/2021,Duff,Errigo,derrigorn@elpais.com,193.84.247.144,France,$3.63,NaN
Female,03/17/2021,Ame,Rastall,arastallro@toplist.cz,188.219.12.109,NaN,$4.59,20.0
Male,03/13/2021,Betty,Stickels,bstickelsrp@cloudflare.com,199.80.60.87,United States,$7.54,20.0
Male,03/17/2021,Paquito,Tesoe,ptesoerq@rakuten.co.jp,0.183.63.11,United States,$5.81,NaN
NaN,03/23/2021,Rochelle,Pringuer,rpringuerrr@house.gov,170.193.249.83,Canada,$8.01,20.0

In [27]:
# Aperçu des données manquantes
df.isnull()
df.notnull()

,date,first_name,last_name,email,ip_address,country,price_paid,tax
gender,,,,,,,,
Male,True,True,True,True,True,True,True,False
Female,True,True,True,True,True,True,True,False
Male,True,True,True,True,True,True,True,True
Female,True,True,True,True,True,True,True,True
Male,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...
Female,True,True,True,True,True,True,True,False
Female,True,True,True,True,True,False,True,True
Male,True,True,True,True,True,True,True,True
Male,True,True,True,True,True,True,True,False
NaN,True,True,True,True,True,True,True,True

In [28]:
# Enlever ces éléments 
df.dropna()

,date,first_name,last_name,email,ip_address,country,price_paid,tax
gender,,,,,,,,
Male,03/17/2021,Erl,Kilminster,ekilminster2@etsy.com,213.8.101.145,United States,$3.73,20.0
Female,03/19/2021,Grata,Brantl,gbrantl3@umn.edu,5.140.237.101,United States,$3.70,20.0
Male,03/24/2021,Kanya,Beasant,kbeasant4@jigsy.com,106.252.162.233,Morocco,$9.24,20.0
Male,03/08/2021,Codi,Feasley,cfeasley7@ed.gov,26.190.191.249,France,$3.01,20.0
Male,03/09/2021,Waylon,Heersema,wheersema8@tumblr.com,63.242.174.112,Canada,$3.70,20.0
...,...,...,...,...,...,...,...,...
Male,03/19/2021,Shep,Thorburn,sthorburnri@prnewswire.com,108.123.252.15,France,$7.02,20.0
Male,03/07/2021,Elihu,Crush,ecrushrj@berkeley.edu,174.38.173.53,Morocco,$5.05,20.0
Female,03/17/2021,Carolyne,Bruntjen,cbruntjenrm@reference.com,7.29.168.78,France,$5.68,20.0
Male,03/13/2021,Betty,Stickels,bstickelsrp@cloudflare.com,199.80.60.87,United States,$7.54,20.0
NaN,03/23/2021,Rochelle,Pringuer,rpringuerrr@house.gov,170.193.249.83,Canada,$8.01,20.0

In [31]:
# Convertir la colonne price_paid 
df.price_paid = df.price_paid.apply(lambda x: x.replace("$", ""))
df.price_paid = df.price_paid.astype(float)

In [32]:
df

,date,first_name,last_name,email,ip_address,country,price_paid,tax
gender,,,,,,,,
Male,03/28/2021,Marylin,Alders,malders0@shop-pro.jp,160.119.8.119,Canada,5.36,NaN
Female,03/19/2021,Hinda,Harridge,hharridge1@gnu.org,210.51.172.132,Canada,8.32,NaN
Male,03/17/2021,Erl,Kilminster,ekilminster2@etsy.com,213.8.101.145,United States,3.73,20.0
Female,03/19/2021,Grata,Brantl,gbrantl3@umn.edu,5.140.237.101,United States,3.70,20.0
Male,03/24/2021,Kanya,Beasant,kbeasant4@jigsy.com,106.252.162.233,Morocco,9.24,20.0
...,...,...,...,...,...,...,...,...
Female,03/24/2021,Duff,Errigo,derrigorn@elpais.com,193.84.247.144,France,3.63,NaN
Female,03/17/2021,Ame,Rastall,arastallro@toplist.cz,188.219.12.109,NaN,4.59,20.0
Male,03/13/2021,Betty,Stickels,bstickelsrp@cloudflare.com,199.80.60.87,United States,7.54,20.0
Male,03/17/2021,Paquito,Tesoe,ptesoerq@rakuten.co.jp,0.183.63.11,United States,5.81,NaN
NaN,03/23/2021,Rochelle,Pringuer,rpringuerrr@house.gov,170.193.249.83,Canada,8.01,20.0

In [41]:
df["tax"] = df["tax"].fillna(0)

In [42]:
df

,date,first_name,last_name,email,ip_address,country,price_paid,tax
gender,,,,,,,,
Male,03/28/2021,Marylin,Alders,malders0@shop-pro.jp,160.119.8.119,Canada,5.36,0.0
Female,03/19/2021,Hinda,Harridge,hharridge1@gnu.org,210.51.172.132,Canada,8.32,0.0
Male,03/17/2021,Erl,Kilminster,ekilminster2@etsy.com,213.8.101.145,United States,3.73,20.0
Female,03/19/2021,Grata,Brantl,gbrantl3@umn.edu,5.140.237.101,United States,3.70,20.0
Male,03/24/2021,Kanya,Beasant,kbeasant4@jigsy.com,106.252.162.233,Morocco,9.24,20.0
...,...,...,...,...,...,...,...,...
Female,03/24/2021,Duff,Errigo,derrigorn@elpais.com,193.84.247.144,France,3.63,0.0
Female,03/17/2021,Ame,Rastall,arastallro@toplist.cz,188.219.12.109,NaN,4.59,20.0
Male,03/13/2021,Betty,Stickels,bstickelsrp@cloudflare.com,199.80.60.87,United States,7.54,20.0
Male,03/17/2021,Paquito,Tesoe,ptesoerq@rakuten.co.jp,0.183.63.11,United States,5.81,0.0
NaN,03/23/2021,Rochelle,Pringuer,rpringuerrr@house.gov,170.193.249.83,Canada,8.01,20.0

In [45]:
# Ajouter une colonne pour le prix total
df["price_net"] = df.price_paid * (1 - df.tax / 100)

In [46]:
df

,date,first_name,last_name,email,ip_address,country,price_paid,tax,price_total
gender,,,,,,,,,
Male,03/28/2021,Marylin,Alders,malders0@shop-pro.jp,160.119.8.119,Canada,5.36,0.0,5.360
Female,03/19/2021,Hinda,Harridge,hharridge1@gnu.org,210.51.172.132,Canada,8.32,0.0,8.320
Male,03/17/2021,Erl,Kilminster,ekilminster2@etsy.com,213.8.101.145,United States,3.73,20.0,2.984
Female,03/19/2021,Grata,Brantl,gbrantl3@umn.edu,5.140.237.101,United States,3.70,20.0,2.960
Male,03/24/2021,Kanya,Beasant,kbeasant4@jigsy.com,106.252.162.233,Morocco,9.24,20.0,7.392
...,...,...,...,...,...,...,...,...,...
Female,03/24/2021,Duff,Errigo,derrigorn@elpais.com,193.84.247.144,France,3.63,0.0,3.630
Female,03/17/2021,Ame,Rastall,arastallro@toplist.cz,188.219.12.109,NaN,4.59,20.0,3.672
Male,03/13/2021,Betty,Stickels,bstickelsrp@cloudflare.com,199.80.60.87,United States,7.54,20.0,6.032
Male,03/17/2021,Paquito,Tesoe,ptesoerq@rakuten.co.jp,0.183.63.11,United States,5.81,0.0,5.810
NaN,03/23/2021,Rochelle,Pringuer,rpringuerrr@house.gov,170.193.249.83,Canada,8.01,20.0,6.408